# Generated by Django 4.2 on 2024-09-07 19:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import storage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('phone', models.IntegerField(validators=[storage.models.validate_phone_number])),
                ('blacklisted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LenderTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='ToolTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('barcode', models.IntegerField(validators=[storage.models.validate_ean13])),
                ('tags', models.ManyToManyField(blank=True, to='storage.tooltag')),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.lender')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.tool')),
            ],
        ),
        migrations.AddField(
            model_name='lender',
            name='team',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='storage.lenderteam'),
        ),
    ]
